//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Input/CameraControlActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CameraControlActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CameraControlActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CameraControlActions"",
    ""maps"": [
        {
            ""name"": ""Camera"",
            ""id"": ""6c076e31-86ff-4fc3-b6e7-9f79dc97dd50"",
            ""actions"": [
                {
                    ""name"": ""Pan_Keyboard"",
                    ""type"": ""Value"",
                    ""id"": ""e6827342-4ad9-400c-9dbb-ebcf0c4a0450"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate_Keyboard"",
                    ""type"": ""Button"",
                    ""id"": ""5c724a6f-e9e0-4791-aa6f-efb02ec3cb8a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pan_Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""90ac112d-e221-4c8e-9ec1-aa298d10de45"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""f9b95638-e1b6-4c4e-9985-8558e8949b7a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom_Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""91c8c515-a92f-442a-b2e8-ef543c24a60d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a3146a42-cf5a-447c-bbb5-ef61b4767d0a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Keyboard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""83b0669b-5235-40e4-bc25-b135b1ac4104"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""72a2ac00-f595-4d5b-bfa8-11ec51c9cb3a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0cfe6742-ec43-4ce7-a54a-a9b9afcef9dd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""93bc1191-e2e1-44cc-889b-1298dd028152"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6c02b788-fc7d-47f9-9661-286337649921"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49ed45b5-77db-4888-938c-a4d60058c47c"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e14b857-fa71-49c0-9b77-a275dd273fec"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom_Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""3ab08aec-f4ff-41a8-a709-f68495fdb398"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate_Keyboard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""103de67e-19d0-49e7-8980-153f6e3e7260"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate_Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5a3b315d-ebf2-4a41-8af7-485a9e64fadd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate_Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_Pan_Keyboard = m_Camera.FindAction("Pan_Keyboard", throwIfNotFound: true);
        m_Camera_Rotate_Keyboard = m_Camera.FindAction("Rotate_Keyboard", throwIfNotFound: true);
        m_Camera_Pan_Mouse = m_Camera.FindAction("Pan_Mouse", throwIfNotFound: true);
        m_Camera_Rotate = m_Camera.FindAction("Rotate", throwIfNotFound: true);
        m_Camera_Zoom_Mouse = m_Camera.FindAction("Zoom_Mouse", throwIfNotFound: true);
    }

    ~@CameraControlActions()
    {
        UnityEngine.Debug.Assert(!m_Camera.enabled, "This will cause a leak and performance issues, CameraControlActions.Camera.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camera
    private readonly InputActionMap m_Camera;
    private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
    private readonly InputAction m_Camera_Pan_Keyboard;
    private readonly InputAction m_Camera_Rotate_Keyboard;
    private readonly InputAction m_Camera_Pan_Mouse;
    private readonly InputAction m_Camera_Rotate;
    private readonly InputAction m_Camera_Zoom_Mouse;
    public struct CameraActions
    {
        private @CameraControlActions m_Wrapper;
        public CameraActions(@CameraControlActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pan_Keyboard => m_Wrapper.m_Camera_Pan_Keyboard;
        public InputAction @Rotate_Keyboard => m_Wrapper.m_Camera_Rotate_Keyboard;
        public InputAction @Pan_Mouse => m_Wrapper.m_Camera_Pan_Mouse;
        public InputAction @Rotate => m_Wrapper.m_Camera_Rotate;
        public InputAction @Zoom_Mouse => m_Wrapper.m_Camera_Zoom_Mouse;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void AddCallbacks(ICameraActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
            @Pan_Keyboard.started += instance.OnPan_Keyboard;
            @Pan_Keyboard.performed += instance.OnPan_Keyboard;
            @Pan_Keyboard.canceled += instance.OnPan_Keyboard;
            @Rotate_Keyboard.started += instance.OnRotate_Keyboard;
            @Rotate_Keyboard.performed += instance.OnRotate_Keyboard;
            @Rotate_Keyboard.canceled += instance.OnRotate_Keyboard;
            @Pan_Mouse.started += instance.OnPan_Mouse;
            @Pan_Mouse.performed += instance.OnPan_Mouse;
            @Pan_Mouse.canceled += instance.OnPan_Mouse;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Zoom_Mouse.started += instance.OnZoom_Mouse;
            @Zoom_Mouse.performed += instance.OnZoom_Mouse;
            @Zoom_Mouse.canceled += instance.OnZoom_Mouse;
        }

        private void UnregisterCallbacks(ICameraActions instance)
        {
            @Pan_Keyboard.started -= instance.OnPan_Keyboard;
            @Pan_Keyboard.performed -= instance.OnPan_Keyboard;
            @Pan_Keyboard.canceled -= instance.OnPan_Keyboard;
            @Rotate_Keyboard.started -= instance.OnRotate_Keyboard;
            @Rotate_Keyboard.performed -= instance.OnRotate_Keyboard;
            @Rotate_Keyboard.canceled -= instance.OnRotate_Keyboard;
            @Pan_Mouse.started -= instance.OnPan_Mouse;
            @Pan_Mouse.performed -= instance.OnPan_Mouse;
            @Pan_Mouse.canceled -= instance.OnPan_Mouse;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Zoom_Mouse.started -= instance.OnZoom_Mouse;
            @Zoom_Mouse.performed -= instance.OnZoom_Mouse;
            @Zoom_Mouse.canceled -= instance.OnZoom_Mouse;
        }

        public void RemoveCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraActions @Camera => new CameraActions(this);
    public interface ICameraActions
    {
        void OnPan_Keyboard(InputAction.CallbackContext context);
        void OnRotate_Keyboard(InputAction.CallbackContext context);
        void OnPan_Mouse(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnZoom_Mouse(InputAction.CallbackContext context);
    }
}
